<?php

use Illuminate\Database\Seeder;

class AdvertCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('advert_categories')->delete();
        
        \DB::table('advert_categories')->insert(array (
            0 => 
            array (
                'id' => 7,
                'name' => '﻿Ремонт общий',
                'slug' => 'remont-obshchiy',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 2,
                'rgt' => 43,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2020-01-09 12:38:11',
                'image' => NULL,
                'icon' => 'icons/a9100ae952f59772748600d28b0ff31f.png',
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            1 => 
            array (
                'id' => 9,
                'name' => 'Ремонт под ключ отдельной комнаты',
                'slug' => 'remont-pod-klyuch-otdelnoy-komnaty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 5,
                'rgt' => 14,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-12-26 11:45:47',
                'image' => 'category/d7e4a22c4df14f78916da9b98e8bb51f.jpg',
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            2 => 
            array (
                'id' => 10,
                'name' => 'Санузел',
                'slug' => 'sanuzel',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 3,
                'lft' => 6,
                'rgt' => 7,
                'parent_id' => 9,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            3 => 
            array (
                'id' => 11,
                'name' => 'Кухня',
                'slug' => 'kukhnya',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 3,
                'lft' => 8,
                'rgt' => 9,
                'parent_id' => 9,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            4 => 
            array (
                'id' => 12,
                'name' => 'Комната',
                'slug' => 'komnata',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 3,
                'lft' => 10,
                'rgt' => 11,
                'parent_id' => 9,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            5 => 
            array (
                'id' => 13,
                'name' => 'Балкон',
                'slug' => 'balkon',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 3,
                'lft' => 12,
                'rgt' => 13,
                'parent_id' => 9,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            6 => 
            array (
                'id' => 14,
                'name' => 'Отделочные работы',
                'slug' => 'otdelochnye-raboty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 15,
                'rgt' => 22,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            7 => 
            array (
                'id' => 15,
                'name' => 'Пол',
                'slug' => 'pol',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 3,
                'lft' => 16,
                'rgt' => 17,
                'parent_id' => 14,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            8 => 
            array (
                'id' => 16,
                'name' => 'Потолок',
                'slug' => 'potolok',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 3,
                'lft' => 18,
                'rgt' => 19,
                'parent_id' => 14,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            9 => 
            array (
                'id' => 17,
                'name' => 'Стены',
                'slug' => 'steny',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 3,
                'lft' => 20,
                'rgt' => 21,
                'parent_id' => 14,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            10 => 
            array (
                'id' => 18,
                'name' => 'Окна и откосы',
                'slug' => 'okna-i-otkosy',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 23,
                'rgt' => 24,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            11 => 
            array (
                'id' => 19,
                'name' => 'Двери входные/межкомнатные',
                'slug' => 'dveri-vkhodnyemezhkomnatnye',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 25,
                'rgt' => 26,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            12 => 
            array (
                'id' => 20,
                'name' => 'Отопление',
                'slug' => 'otoplenie',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 27,
                'rgt' => 28,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            13 => 
            array (
                'id' => 21,
                'name' => 'Сантехнические работы',
                'slug' => 'santekhnicheskie-raboty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 29,
                'rgt' => 30,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            14 => 
            array (
                'id' => 22,
                'name' => 'Эмалировка ванн/вкладыши',
                'slug' => 'emalirovka-vannvkladyshi',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 31,
                'rgt' => 32,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            15 => 
            array (
                'id' => 23,
                'name' => 'Водоснабжение/канализация',
                'slug' => 'vodosnabzheniekanalizatsiya',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 33,
                'rgt' => 34,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            16 => 
            array (
                'id' => 24,
                'name' => 'Электрика',
                'slug' => 'elektrika',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 35,
                'rgt' => 36,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            17 => 
            array (
                'id' => 25,
                'name' => 'Теплый пол',
                'slug' => 'teplyy-pol',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 37,
                'rgt' => 38,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            18 => 
            array (
                'id' => 26,
                'name' => 'Кондиционеры и вентиляция',
                'slug' => 'konditsionery-i-ventilyatsiya',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 39,
                'rgt' => 40,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            19 => 
            array (
                'id' => 27,
                'name' => 'Алмазная резка и сверление',
                'slug' => 'almaznaya-rezka-i-sverlenie',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 41,
                'rgt' => 42,
                'parent_id' => 7,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            20 => 
            array (
                'id' => 29,
                'name' => 'Наружная отделка/фасадные работы',
                'slug' => 'naruzhnaya-otdelkafasadnye-raboty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 45,
                'rgt' => 46,
                'parent_id' => 28,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            21 => 
            array (
                'id' => 30,
                'name' => 'Кровля',
                'slug' => 'krovlya',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 47,
                'rgt' => 48,
                'parent_id' => 28,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            22 => 
            array (
                'id' => 31,
                'name' => 'Погреб',
                'slug' => 'pogreb',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 49,
                'rgt' => 50,
                'parent_id' => 28,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            23 => 
            array (
                'id' => 32,
                'name' => 'Бассейн',
                'slug' => 'basseyn',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 51,
                'rgt' => 52,
                'parent_id' => 28,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            24 => 
            array (
                'id' => 33,
                'name' => 'Колодец/выгребная яма',
                'slug' => 'kolodetsvygrebnaya-yama',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 53,
                'rgt' => 54,
                'parent_id' => 28,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            25 => 
            array (
                'id' => 34,
                'name' => 'Лестницы',
                'slug' => 'lestnitsy',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 55,
                'rgt' => 56,
                'parent_id' => 28,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            26 => 
            array (
                'id' => 35,
                'name' => 'Печи/камины',
                'slug' => 'pechikaminy',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 57,
                'rgt' => 58,
                'parent_id' => 28,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            27 => 
            array (
                'id' => 36,
                'name' => 'Ковка/литье',
                'slug' => 'kovkalite',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 59,
                'rgt' => 60,
                'parent_id' => 28,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            28 => 
            array (
                'id' => 37,
                'name' => 'Проектирование/смета',
                'slug' => 'proektirovaniesmeta',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 62,
                'rgt' => 73,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            29 => 
            array (
                'id' => 38,
                'name' => 'Сметные работы',
                'slug' => 'smetnye-raboty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 63,
                'rgt' => 64,
                'parent_id' => 37,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            30 => 
            array (
                'id' => 39,
                'name' => 'Проектирование зданий',
                'slug' => 'proektirovanie-zdaniy',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 65,
                'rgt' => 66,
                'parent_id' => 37,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            31 => 
            array (
                'id' => 40,
                'name' => 'Геодезические работы',
                'slug' => 'geodezicheskie-raboty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 67,
                'rgt' => 68,
                'parent_id' => 37,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            32 => 
            array (
                'id' => 41,
                'name' => 'Межевание/кадастр',
                'slug' => 'mezhevaniekadastr',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 69,
                'rgt' => 70,
                'parent_id' => 37,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            33 => 
            array (
                'id' => 42,
                'name' => 'Оформление перепланировок',
                'slug' => 'oformlenie-pereplanirovok',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 71,
                'rgt' => 72,
                'parent_id' => 37,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            34 => 
            array (
                'id' => 43,
                'name' => 'Строительство',
                'slug' => 'stroitelstvo',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 74,
                'rgt' => 93,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            35 => 
            array (
                'id' => 44,
                'name' => 'Построить дом',
                'slug' => 'postroit-dom',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 75,
                'rgt' => 76,
                'parent_id' => 43,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            36 => 
            array (
                'id' => 45,
                'name' => 'Построить баню/сауну',
                'slug' => 'postroit-banyusaunu',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 77,
                'rgt' => 78,
                'parent_id' => 43,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            37 => 
            array (
                'id' => 46,
                'name' => 'Построить беседку',
                'slug' => 'postroit-besedku',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 79,
                'rgt' => 80,
                'parent_id' => 43,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            38 => 
            array (
                'id' => 47,
                'name' => 'Построить теплицу',
                'slug' => 'postroit-teplitsu',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 81,
                'rgt' => 82,
                'parent_id' => 43,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            39 => 
            array (
                'id' => 48,
                'name' => 'Построить гараж',
                'slug' => 'postroit-garazh',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 83,
                'rgt' => 84,
                'parent_id' => 43,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            40 => 
            array (
                'id' => 49,
                'name' => 'Построить сруб',
                'slug' => 'postroit-srub',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 85,
                'rgt' => 86,
                'parent_id' => 43,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            41 => 
            array (
                'id' => 50,
                'name' => 'Заборы/ограждения',
                'slug' => 'zaboryograzhdeniya',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 87,
                'rgt' => 88,
                'parent_id' => 43,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            42 => 
            array (
                'id' => 51,
                'name' => 'Фундамент/бетонные работы',
                'slug' => 'fundamentbetonnye-raboty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 89,
                'rgt' => 90,
                'parent_id' => 43,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            43 => 
            array (
                'id' => 52,
                'name' => 'Другие мелкие постройки',
                'slug' => 'drugie-melkie-postroyki',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 91,
                'rgt' => 92,
                'parent_id' => 43,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            44 => 
            array (
                'id' => 53,
                'name' => 'Грузчики/грузовики',
                'slug' => 'gruzchikigruzoviki',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 94,
                'rgt' => 101,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            45 => 
            array (
                'id' => 54,
                'name' => 'Вывоз мусора',
                'slug' => 'vyvoz-musora',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 95,
                'rgt' => 96,
                'parent_id' => 53,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            46 => 
            array (
                'id' => 55,
                'name' => 'Переезд',
                'slug' => 'pereezd',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 97,
                'rgt' => 98,
                'parent_id' => 53,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            47 => 
            array (
                'id' => 56,
                'name' => 'Услуги грузчиков',
                'slug' => 'uslugi-gruzchikov',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 99,
                'rgt' => 100,
                'parent_id' => 53,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            48 => 
            array (
                'id' => 57,
                'name' => 'Участок',
                'slug' => 'uchastok',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 102,
                'rgt' => 113,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            49 => 
            array (
                'id' => 58,
                'name' => 'Ландшафтный дизайн',
                'slug' => 'landshaftnyy-dizayn',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 103,
                'rgt' => 104,
                'parent_id' => 57,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            50 => 
            array (
                'id' => 59,
                'name' => 'Озеленение',
                'slug' => 'ozelenenie',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 105,
                'rgt' => 106,
                'parent_id' => 57,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            51 => 
            array (
                'id' => 60,
                'name' => 'Системы полива огорода',
                'slug' => 'sistemy-poliva-ogoroda',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 107,
                'rgt' => 108,
                'parent_id' => 57,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            52 => 
            array (
                'id' => 61,
                'name' => 'Уличное освещение',
                'slug' => 'ulichnoe-osveshchenie',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 109,
                'rgt' => 110,
                'parent_id' => 57,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            53 => 
            array (
                'id' => 62,
                'name' => 'Искусственные водоемы/фонтаны',
                'slug' => 'iskusstvennye-vodoemyfontany',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 111,
                'rgt' => 112,
                'parent_id' => 57,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            54 => 
            array (
                'id' => 63,
                'name' => 'Мастер на час/мелкие бытовые услуги',
                'slug' => 'master-na-chasmelkie-bytovye-uslugi',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 114,
                'rgt' => 115,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            55 => 
            array (
                'id' => 64,
                'name' => 'Демонтаж/снос',
                'slug' => 'demontazhsnos',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 116,
                'rgt' => 117,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            56 => 
            array (
                'id' => 65,
                'name' => 'Бурение скважин',
                'slug' => 'burenie-skvazhin',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 118,
                'rgt' => 119,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            57 => 
            array (
                'id' => 66,
                'name' => 'Рольставни/секционные ворота',
                'slug' => 'rolstavnisektsionnye-vorota',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 120,
                'rgt' => 121,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            58 => 
            array (
                'id' => 67,
                'name' => 'Сварочные работы',
                'slug' => 'svarochnye-raboty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 122,
                'rgt' => 123,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            59 => 
            array (
                'id' => 68,
                'name' => 'Столярные/плотницкие работы',
                'slug' => 'stolyarnyeplotnitskie-raboty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 124,
                'rgt' => 125,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            60 => 
            array (
                'id' => 69,
                'name' => 'Высотные работы',
                'slug' => 'vysotnye-raboty',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 126,
                'rgt' => 127,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            61 => 
            array (
                'id' => 70,
                'name' => 'Сигнализация/видеонаблюдение',
                'slug' => 'signalizatsiyavideonablyudenie',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 128,
                'rgt' => 129,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            62 => 
            array (
                'id' => 71,
                'name' => 'Установка/вскрытие замков',
                'slug' => 'ustanovkavskrytie-zamkov',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 130,
                'rgt' => 131,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            63 => 
            array (
                'id' => 72,
                'name' => 'Аренда инструмента/спецтехники',
                'slug' => 'arenda-instrumentaspetstekhniki',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 132,
                'rgt' => 137,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            64 => 
            array (
                'id' => 73,
                'name' => 'Аренда инструмента и оборудования',
                'slug' => 'arenda-instrumenta-i-oborudovaniya',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 133,
                'rgt' => 134,
                'parent_id' => 72,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            65 => 
            array (
                'id' => 74,
                'name' => 'Аренда спецтехники',
                'slug' => 'arenda-spetstekhniki',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 135,
                'rgt' => 136,
                'parent_id' => 72,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            66 => 
            array (
                'id' => 75,
                'name' => 'Мебель/интерьер/дизайн',
                'slug' => 'mebelintererdizayn',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 138,
                'rgt' => 147,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            67 => 
            array (
                'id' => 76,
                'name' => 'Проекты интерьеров',
                'slug' => 'proekty-intererov',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 139,
                'rgt' => 140,
                'parent_id' => 75,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            68 => 
            array (
                'id' => 77,
                'name' => 'Изготовление мебели на заказ',
                'slug' => 'izgotovlenie-mebeli-na-zakaz',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 141,
                'rgt' => 142,
                'parent_id' => 75,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            69 => 
            array (
                'id' => 78,
                'name' => 'Шторы/карнизы/жалюзи',
                'slug' => 'shtorykarnizyzhalyuzi',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 143,
                'rgt' => 144,
                'parent_id' => 75,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            70 => 
            array (
                'id' => 79,
                'name' => 'Чехлы/покрывала',
                'slug' => 'chekhlypokryvala',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 145,
                'rgt' => 146,
                'parent_id' => 75,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            71 => 
            array (
                'id' => 80,
                'name' => 'Телевидение/интернет',
                'slug' => 'televidenieinternet',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 148,
                'rgt' => 153,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            72 => 
            array (
                'id' => 81,
                'name' => 'Интернет',
                'slug' => 'internet',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 149,
                'rgt' => 150,
                'parent_id' => 80,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            73 => 
            array (
                'id' => 82,
                'name' => 'Телевидение',
                'slug' => 'televidenie',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 151,
                'rgt' => 152,
                'parent_id' => 80,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            74 => 
            array (
                'id' => 83,
                'name' => 'Ремонт/установка техники',
                'slug' => 'remontustanovka-tekhniki',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 154,
                'rgt' => 159,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            75 => 
            array (
                'id' => 84,
                'name' => 'Ремонт бытовой техники',
                'slug' => 'remont-bytovoy-tekhniki',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 155,
                'rgt' => 156,
                'parent_id' => 83,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            76 => 
            array (
                'id' => 85,
                'name' => 'Установка/подключение',
                'slug' => 'ustanovkapodklyuchenie',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 157,
                'rgt' => 158,
                'parent_id' => 83,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            77 => 
            array (
                'id' => 86,
                'name' => 'Ремонт строительного инструмента',
                'slug' => 'remont-stroitelnogo-instrumenta',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 160,
                'rgt' => 161,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            78 => 
            array (
                'id' => 87,
                'name' => 'Уборка/Клининг',
                'slug' => 'uborkaklining',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 162,
                'rgt' => 163,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            79 => 
            array (
                'id' => 88,
                'name' => 'Юридические услуги',
                'slug' => 'yuridicheskie-uslugi',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 1,
                'lft' => 164,
                'rgt' => 173,
                'parent_id' => NULL,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            80 => 
            array (
                'id' => 89,
                'name' => 'Консультации',
                'slug' => 'konsultatsii',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 165,
                'rgt' => 166,
                'parent_id' => 88,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            81 => 
            array (
                'id' => 90,
                'name' => 'Сопровождение сделок',
                'slug' => 'soprovozhdenie-sdelok',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 167,
                'rgt' => 168,
                'parent_id' => 88,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            82 => 
            array (
                'id' => 91,
                'name' => 'Страхование',
                'slug' => 'strakhovanie',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 169,
                'rgt' => 170,
                'parent_id' => 88,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
            83 => 
            array (
                'id' => 92,
                'name' => 'Прочие юридические услуги',
                'slug' => 'prochie-yuridicheskie-uslugi',
                'breadcrumb_name' => NULL,
                'is_visible' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'seo_text' => NULL,
                'depth' => 2,
                'lft' => 171,
                'rgt' => 172,
                'parent_id' => 88,
                'created_at' => '2019-10-04 05:53:31',
                'updated_at' => '2019-10-04 05:53:43',
                'image' => NULL,
                'icon' => NULL,
                'icon_work_category' => NULL,
                'dimension_id' => NULL,
            ),
        ));
        
        
    }
}