<?php

use Illuminate\Database\Seeder;

class LocationsSeeder extends Seeder
{
    public function run()
    {
        // create cities
        DB::statement("INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (1, 'Москва', 'moskva', null, '2020-03-06 15:43:12', 55.75321500, 37.62250400);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (3, 'Санкт-Петербург', 'sankt-peterburg', '2020-03-06 15:47:08', '2020-03-06 15:47:33', 59.93909500, 30.31586800);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (4, 'Владивосток', 'vladivostok', '2020-03-12 13:23:41', '2020-03-12 13:23:41', 43.11553600, 131.88548500);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (5, 'Волгоград', 'volgograd', '2020-03-12 13:24:03', '2020-03-12 13:24:03', 48.70707300, 44.51693000);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (6, 'Воронеж', 'voronezh', '2020-03-12 13:24:11', '2020-03-12 13:24:11', 51.66078100, 39.20026900);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (7, 'Екатеринбург', 'ekaterinburg', '2020-03-12 13:24:20', '2020-03-12 13:24:20', 56.83801100, 60.59746500);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (8, 'Казань', 'kazan', '2020-03-12 13:24:28', '2020-03-12 13:24:28', 55.79628900, 49.10879500);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (9, 'Краснодар', 'krasnodar', '2020-03-12 13:24:34', '2020-03-12 13:24:34', 45.03547000, 38.97531300);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (10, 'Красноярск', 'krasnoyarsk', '2020-03-12 13:24:39', '2020-03-12 13:24:39', 56.01056300, 92.85257200);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (11, 'Крым', 'krym', '2020-03-12 13:25:16', '2020-03-12 13:25:16', 45.38919400, 33.99375100);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (12, 'Нижний Новгород', 'nizhniy-novgorod', '2020-03-12 13:26:07', '2020-03-12 13:26:07', 56.32679700, 44.00651600);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (13, 'Новосибирск', 'novosibirsk', '2020-03-12 13:26:16', '2020-03-12 13:26:16', 55.03019900, 82.92043000);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (14, 'Омск', 'omsk', '2020-03-12 13:26:23', '2020-03-12 13:26:23', 54.98934200, 73.36821200);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (15, 'Пермь', 'perm', '2020-03-12 13:26:29', '2020-03-12 13:26:29', 58.01045000, 56.22943400);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (16, 'Ростов-на-Дону', 'rostov-na-donu', '2020-03-12 13:26:33', '2020-03-12 13:26:33', 47.22207800, 39.72034900);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (17, 'Самара', 'samara', '2020-03-12 13:26:39', '2020-03-12 13:26:39', 53.19553800, 50.10178300);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (19, 'Саратов', 'saratov', '2020-03-12 13:26:55', '2020-03-12 13:26:55', 51.53310300, 46.03415800);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (20, 'Севастополь', 'sevastopol', '2020-03-12 13:27:01', '2020-03-12 13:27:01', 44.61660400, 33.52536900);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (21, 'Уфа', 'ufa', '2020-03-12 13:27:07', '2020-03-12 13:27:07', 54.73514700, 55.95872700);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (22, 'Хабаровск', 'habarovsk', '2020-03-12 13:27:13', '2020-03-12 13:27:13', 48.48022300, 135.07191700);
INSERT INTO cities (id, name, slug, created_at, updated_at, map_lat, map_long) VALUES (23, 'Челябинск', 'chelyabinsk', '2020-03-12 13:27:19', '2020-03-12 13:27:19', 55.15989700, 61.40255400);");

        // create districts
        DB::statement("INSERT INTO city_districts (id, name, slug, city_id) VALUES (5, 'район Арбат', 'rayon-arbat', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (6, 'Басманный район', 'basmannyy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (7, 'район Замоскворечье', 'rayon-zamoskvoreche', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (8, 'Красносельский район', 'krasnoselskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (9, 'Мещанский район', 'meshchanskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (10, 'Пресненский район', 'presnenskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (11, 'Таганский район', 'taganskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (12, 'Тверской район', 'tverskoy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (13, 'район Хамовники', 'rayon-hamovniki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (14, 'район Якиманка', 'rayon-yakimanka', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (15, 'район Аэропорт', 'rayon-aeroport', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (16, 'Беговой район', 'begovoy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (17, 'Бескудниковский район', 'beskudnikovskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (18, 'Войковский район', 'voykovskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (19, 'район Восточное Дегунино', 'rayon-vostochnoe-degunino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (20, 'Головинский район', 'golovinskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (21, 'Дмитровский район', 'dmitrovskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (22, 'район Западное Дегунино', 'rayon-zapadnoe-degunino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (23, 'район Коптево', 'rayon-koptevo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (24, 'Левобережный район', 'levoberezhnyy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (25, 'Молжаниновский район', 'molzhaninovskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (26, 'Савёловский район', 'savelovskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (27, 'район Сокол', 'rayon-sokol', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (28, 'Тимирязевский район', 'timiryazevskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (29, 'район Ховрино', 'rayon-hovrino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (30, 'Хорошёвский район', 'horoshevskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (31, 'Алексеевский район', 'alekseevskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (32, 'Алтуфьевский район', 'altufevskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (33, 'Бабушкинский район', 'babushkinskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (34, 'район Бибирево', 'rayon-bibirevo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (35, 'Бутырский район', 'butyrskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (36, 'район Лианозово', 'rayon-lianozovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (37, 'Лосиноостровский район', 'losinoostrovskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (38, 'район Марфино', 'rayon-marfino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (39, 'район Марьина Роща', 'rayon-marina-roshcha', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (40, 'Останкинский район', 'ostankinskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (41, 'район Отрадное', 'rayon-otradnoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (42, 'район Ростокино', 'rayon-rostokino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (43, 'район Свиблово', 'rayon-sviblovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (44, 'Северный район', 'severnyy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (45, 'район Северное Медведково', 'rayon-severnoe-medvedkovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (46, 'район Южное Медведково', 'rayon-yuzhnoe-medvedkovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (47, 'Ярославский район', 'yaroslavskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (48, 'район Богородское', 'rayon-bogorodskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (49, 'район Вешняки', 'rayon-veshnyaki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (50, 'Восточный район', 'vostochnyy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (51, 'район Восточное Измайлово', 'rayon-vostochnoe-izmaylovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (52, 'район Гольяново', 'rayon-golyanovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (53, 'район Ивановское', 'rayon-ivanovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (54, 'район Измайлово', 'rayon-izmaylovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (55, 'Косино-Ухтомский район', 'kosino-uhtomskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (56, 'район Метрогородок', 'rayon-metrogorodok', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (57, 'район Новогиреево', 'rayon-novogireevo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (58, 'район Новокосино', 'rayon-novokosino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (59, 'район Перово', 'rayon-perovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (60, 'район Преображенское', 'rayon-preobrazhenskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (61, 'район Северное Измайлово', 'rayon-severnoe-izmaylovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (62, 'район Соколиная Гора', 'rayon-sokolinaya-gora', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (63, 'район Сокольники', 'rayon-sokolniki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (64, 'район Выхино-Жулебино', 'rayon-vyhino-zhulebino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (65, 'район Капотня', 'rayon-kapotnya', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (66, 'район Кузьминки', 'rayon-kuzminki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (67, 'район Лефортово', 'rayon-lefortovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (68, 'район Люблино', 'rayon-lyublino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (69, 'район Марьино', 'rayon-marino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (70, 'район Некрасовка', 'rayon-nekrasovka', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (71, 'Нижегородский район', 'nizhegorodskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (72, 'район Печатники', 'rayon-pechatniki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (73, 'Рязанский район', 'ryazanskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (74, 'район Текстильщики', 'rayon-tekstilshchiki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (75, 'Южнопортовый район', 'yuzhnoportovyy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (76, 'район Бирюлёво Восточное', 'rayon-biryulevo-vostochnoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (77, 'район Бирюлёво Западное', 'rayon-biryulevo-zapadnoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (78, 'район Братеево', 'rayon-brateevo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (79, 'Даниловский район', 'danilovskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (80, 'Донской район', 'donskoy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (81, 'район Зябликово', 'rayon-zyablikovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (82, 'район Москворечье-Сабурово', 'rayon-moskvoreche-saburovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (83, 'район Нагатино-Садовники', 'rayon-nagatino-sadovniki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (84, 'район Нагатинский Затон', 'rayon-nagatinskiy-zaton', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (85, 'Нагорный район', 'nagornyy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (86, 'район Орехово-Борисово Северное', 'rayon-orehovo-borisovo-severnoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (87, 'район Орехово-Борисово Южное', 'rayon-orehovo-borisovo-yuzhnoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (88, 'район Царицыно', 'rayon-caricyno', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (89, 'район Чертаново Северное', 'rayon-chertanovo-severnoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (90, 'район Чертаново Центральное', 'rayon-chertanovo-centralnoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (91, 'район Чертаново Южное', 'rayon-chertanovo-yuzhnoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (92, 'Академический район', 'akademicheskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (93, 'Гагаринский район', 'gagarinskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (94, 'район Зюзино', 'rayon-zyuzino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (95, 'район Коньково', 'rayon-konkovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (96, 'район Котловка', 'rayon-kotlovka', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (97, 'Ломоносовский район', 'lomonosovskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (98, 'Обручевский район', 'obruchevskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (99, 'район Северное Бутово', 'rayon-severnoe-butovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (100, 'район Тёплый Стан', 'rayon-teplyy-stan', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (101, 'район Черёмушки', 'rayon-cheremushki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (102, 'район Южное Бутово', 'rayon-yuzhnoe-butovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (103, 'район Ясенево', 'rayon-yasenevo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (104, 'район Дорогомилово', 'rayon-dorogomilovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (105, 'район Крылатское', 'rayon-krylatskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (106, 'район Кунцево', 'rayon-kuncevo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (107, 'Можайский район', 'mozhayskiy-rayon', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (108, 'район Ново-Переделкино', 'rayon-novo-peredelkino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (109, 'район Очаково-Матвеевское', 'rayon-ochakovo-matveevskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (110, 'район Проспект Вернадского', 'rayon-prospekt-vernadskogo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (111, 'район Раменки', 'rayon-ramenki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (112, 'район Солнцево', 'rayon-solncevo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (113, 'район Тропарёво-Никулино', 'rayon-troparevo-nikulino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (114, 'район Филёвский Парк', 'rayon-filevskiy-park', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (115, 'район Фили-Давыдково', 'rayon-fili-davydkovo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (116, 'район Куркино', 'rayon-kurkino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (117, 'район Митино', 'rayon-mitino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (118, 'район Покровское-Стрешнево', 'rayon-pokrovskoe-streshnevo', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (119, 'район Северное Тушино', 'rayon-severnoe-tushino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (120, 'район Хорошёво-Мнёвники', 'rayon-horoshevo-mnevniki', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (121, 'район Щукино', 'rayon-shchukino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (122, 'район Южное Тушино', 'rayon-yuzhnoe-tushino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (123, 'район Строгино', 'rayon-strogino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (124, 'район СП Внуковское', 'rayon-sp-vnukovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (125, 'район СП Воскресенское', 'rayon-sp-voskresenskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (126, 'район СП Десёновское', 'rayon-sp-desenovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (127, 'район СП Кокошкино', 'rayon-sp-kokoshkino', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (128, 'район СП Марушкинское', 'rayon-sp-marushkinskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (129, 'район СП Московский', 'rayon-sp-moskovskiy', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (130, 'район СП Мосрентген', 'rayon-sp-mosrentgen', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (131, 'район СП Рязановское', 'rayon-sp-ryazanovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (132, 'район СП Сосенское', 'rayon-sp-sosenskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (133, 'район СП Филимонковское', 'rayon-sp-filimonkovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (134, 'район ГО Щербинка', 'rayon-go-shcherbinka', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (135, 'район СП Вороновское', 'rayon-sp-voronovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (136, 'район СП Киевский', 'rayon-sp-kievskiy', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (137, 'район СП Клёновское', 'rayon-sp-klenovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (138, 'район СП Краснопахорское', 'rayon-sp-krasnopahorskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (139, 'район СП Михайлово-Ярцевское', 'rayon-sp-mihaylovo-yarcevskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (140, 'район СП Новофёдоровское', 'rayon-sp-novofedorovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (141, 'район СП Первомайское', 'rayon-sp-pervomayskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (142, 'район СП Роговское', 'rayon-sp-rogovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (143, 'район ГО Троицк', 'rayon-go-troick', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (144, 'район СП Щаповское', 'rayon-sp-shchapovskoe', 1);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (145, 'Адмиралтейский район', 'admiralteyskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (146, 'Василеостровский район', 'vasileostrovskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (147, 'Выборгский район', 'vyborgskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (148, 'Калининский район', 'kalininskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (149, 'Кировский район', 'kirovskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (150, 'Колпинский район', 'kolpinskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (151, 'Красногвардейский район', 'krasnogvardeyskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (152, 'Красносельский район', 'krasnoselskiy-rayon-1', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (153, 'Кронштадтский район', 'kronshtadtskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (154, 'Курортный район', 'kurortnyy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (155, 'Московский район', 'moskovskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (156, 'Невский район', 'nevskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (157, 'Петроградский район', 'petrogradskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (158, 'Петродворцовый район', 'petrodvorcovyy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (159, 'Приморский район', 'primorskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (160, 'Пушкинский район', 'pushkinskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (161, 'Фрунзенский район', 'frunzenskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (162, 'Центральный район', 'centralnyy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (163, 'Ленсоветовский район', 'lensovetovskiy-rayon', 3);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (164, 'Фрунзенский район', 'frunzenskiy-rayon-1', 4);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (165, 'Советский район', 'sovetskiy-rayon', 4);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (166, 'Первореченский район', 'pervorechenskiy-rayon', 4);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (167, 'Первомайский район', 'pervomayskiy-rayon', 4);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (168, 'Ленинский район', 'leninskiy-rayon', 4);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (169, 'Центральный район', 'centralnyy-rayon-1', 5);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (170, 'Тракторозаводский район', 'traktorozavodskiy-rayon', 5);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (171, 'Советский район', 'sovetskiy-rayon-1', 5);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (172, 'Краснооктябрьский район', 'krasnooktyabrskiy-rayon', 5);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (173, 'Красноармейский район', 'krasnoarmeyskiy-rayon', 5);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (174, 'Кировский район', 'kirovskiy-rayon-1', 5);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (175, 'Дзержинский район', 'dzerzhinskiy-rayon', 5);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (176, 'Ворошиловский район', 'voroshilovskiy-rayon', 5);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (177, 'Центральный район', 'centralnyy-rayon-2', 6);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (178, 'Советский район', 'sovetskiy-rayon-2', 6);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (179, 'Ленинский район', 'leninskiy-rayon-1', 6);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (180, 'Левобережный район', 'levoberezhnyy-rayon-1', 6);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (181, 'Коминтерновский район', 'kominternovskiy-rayon', 6);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (182, 'Железнодорожный район', 'zheleznodorozhnyy-rayon', 6);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (183, 'Чкаловский район', 'chkalovskiy-rayon', 7);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (184, 'Орджоникидзевский район', 'ordzhonikidzevskiy-rayon', 7);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (185, 'Октябрьский район', 'oktyabrskiy-rayon', 7);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (186, 'Ленинский район', 'leninskiy-rayon-2', 7);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (187, 'Кировский район', 'kirovskiy-rayon-2', 7);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (188, 'Железнодорожный район', 'zheleznodorozhnyy-rayon-1', 7);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (189, 'Верх-Исетский район', 'verh-isetskiy-rayon', 7);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (190, 'Советский район', 'sovetskiy-rayon-3', 8);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (191, 'Приволжский район', 'privolzhskiy-rayon', 8);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (192, 'Ново-Савиновский район', 'novo-savinovskiy-rayon', 8);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (193, 'Московский район', 'moskovskiy-rayon-1', 8);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (194, 'Кировский район', 'kirovskiy-rayon-3', 8);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (195, 'Вахитовский район', 'vahitovskiy-rayon', 8);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (196, 'Авиастроительный район', 'aviastroitelnyy-rayon', 8);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (197, 'Центральный район', 'centralnyy-rayon-3', 9);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (198, 'Прикубанский район', 'prikubanskiy-rayon', 9);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (199, 'Карасунский район', 'karasunskiy-rayon', 9);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (200, 'Западный район', 'zapadnyy-rayon', 9);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (201, 'Центральный район', 'centralnyy-rayon-4', 10);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (202, 'Советский район', 'sovetskiy-rayon-4', 10);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (203, 'Свердловский район', 'sverdlovskiy-rayon', 10);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (204, 'Октябрьский район', 'oktyabrskiy-rayon-1', 10);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (205, 'Ленинский район', 'leninskiy-rayon-3', 10);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (206, 'Кировский район', 'kirovskiy-rayon-4', 10);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (207, 'Железнодорожный район', 'zheleznodorozhnyy-rayon-2', 10);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (208, 'район Арбат', 'rayon-arbat-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (209, 'Басманный район', 'basmannyy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (210, 'район Замоскворечье', 'rayon-zamoskvoreche-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (211, 'Красносельский район', 'krasnoselskiy-rayon-2', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (212, 'Мещанский район', 'meshchanskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (213, 'Пресненский район', 'presnenskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (214, 'Таганский район', 'taganskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (215, 'Тверской район', 'tverskoy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (216, 'район Хамовники', 'rayon-hamovniki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (217, 'район Якиманка', 'rayon-yakimanka-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (218, 'район Аэропорт', 'rayon-aeroport-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (219, 'Беговой район', 'begovoy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (220, 'Бескудниковский район', 'beskudnikovskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (221, 'Войковский район', 'voykovskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (222, 'район Восточное Дегунино', 'rayon-vostochnoe-degunino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (223, 'Головинский район', 'golovinskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (224, 'Дмитровский район', 'dmitrovskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (225, 'район Западное Дегунино', 'rayon-zapadnoe-degunino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (226, 'район Коптево', 'rayon-koptevo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (227, 'Левобережный район', 'levoberezhnyy-rayon-2', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (228, 'Молжаниновский район', 'molzhaninovskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (229, 'Савёловский район', 'savelovskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (230, 'район Сокол', 'rayon-sokol-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (231, 'Тимирязевский район', 'timiryazevskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (232, 'район Ховрино', 'rayon-hovrino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (233, 'Хорошёвский район', 'horoshevskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (234, 'Алексеевский район', 'alekseevskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (235, 'Алтуфьевский район', 'altufevskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (236, 'Бабушкинский район', 'babushkinskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (237, 'район Бибирево', 'rayon-bibirevo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (238, 'Бутырский район', 'butyrskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (239, 'район Лианозово', 'rayon-lianozovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (240, 'Лосиноостровский район', 'losinoostrovskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (241, 'район Марфино', 'rayon-marfino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (242, 'район Марьина Роща', 'rayon-marina-roshcha-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (243, 'Останкинский район', 'ostankinskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (244, 'район Отрадное', 'rayon-otradnoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (245, 'район Ростокино', 'rayon-rostokino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (246, 'район Свиблово', 'rayon-sviblovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (247, 'Северный район', 'severnyy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (248, 'район Северное Медведково', 'rayon-severnoe-medvedkovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (249, 'район Южное Медведково', 'rayon-yuzhnoe-medvedkovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (250, 'Ярославский район', 'yaroslavskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (251, 'район Богородское', 'rayon-bogorodskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (252, 'район Вешняки', 'rayon-veshnyaki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (253, 'Восточный район', 'vostochnyy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (254, 'район Восточное Измайлово', 'rayon-vostochnoe-izmaylovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (255, 'район Гольяново', 'rayon-golyanovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (256, 'район Ивановское', 'rayon-ivanovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (257, 'район Измайлово', 'rayon-izmaylovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (258, 'Косино-Ухтомский район', 'kosino-uhtomskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (259, 'район Метрогородок', 'rayon-metrogorodok-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (260, 'район Новогиреево', 'rayon-novogireevo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (261, 'район Новокосино', 'rayon-novokosino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (262, 'район Перово', 'rayon-perovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (263, 'район Преображенское', 'rayon-preobrazhenskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (264, 'район Северное Измайлово', 'rayon-severnoe-izmaylovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (265, 'район Соколиная Гора', 'rayon-sokolinaya-gora-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (266, 'район Сокольники', 'rayon-sokolniki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (267, 'район Выхино-Жулебино', 'rayon-vyhino-zhulebino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (268, 'район Капотня', 'rayon-kapotnya-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (269, 'район Кузьминки', 'rayon-kuzminki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (270, 'район Лефортово', 'rayon-lefortovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (271, 'район Люблино', 'rayon-lyublino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (272, 'район Марьино', 'rayon-marino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (273, 'район Некрасовка', 'rayon-nekrasovka-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (274, 'Нижегородский район', 'nizhegorodskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (275, 'район Печатники', 'rayon-pechatniki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (276, 'Рязанский район', 'ryazanskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (277, 'район Текстильщики', 'rayon-tekstilshchiki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (278, 'Южнопортовый район', 'yuzhnoportovyy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (279, 'район Бирюлёво Восточное', 'rayon-biryulevo-vostochnoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (280, 'район Бирюлёво Западное', 'rayon-biryulevo-zapadnoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (281, 'район Братеево', 'rayon-brateevo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (282, 'Даниловский район', 'danilovskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (283, 'Донской район', 'donskoy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (284, 'район Зябликово', 'rayon-zyablikovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (285, 'район Москворечье-Сабурово', 'rayon-moskvoreche-saburovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (286, 'район Нагатино-Садовники', 'rayon-nagatino-sadovniki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (287, 'район Нагатинский Затон', 'rayon-nagatinskiy-zaton-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (288, 'Нагорный район', 'nagornyy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (289, 'район Орехово-Борисово Северное', 'rayon-orehovo-borisovo-severnoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (290, 'район Орехово-Борисово Южное', 'rayon-orehovo-borisovo-yuzhnoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (291, 'район Царицыно', 'rayon-caricyno-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (292, 'район Чертаново Северное', 'rayon-chertanovo-severnoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (293, 'район Чертаново Центральное', 'rayon-chertanovo-centralnoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (294, 'район Чертаново Южное', 'rayon-chertanovo-yuzhnoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (295, 'Академический район', 'akademicheskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (296, 'Гагаринский район', 'gagarinskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (297, 'район Зюзино', 'rayon-zyuzino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (298, 'район Коньково', 'rayon-konkovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (299, 'район Котловка', 'rayon-kotlovka-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (300, 'Ломоносовский район', 'lomonosovskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (301, 'Обручевский район', 'obruchevskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (302, 'район Северное Бутово', 'rayon-severnoe-butovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (303, 'район Тёплый Стан', 'rayon-teplyy-stan-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (304, 'район Черёмушки', 'rayon-cheremushki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (305, 'район Южное Бутово', 'rayon-yuzhnoe-butovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (306, 'район Ясенево', 'rayon-yasenevo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (307, 'район Дорогомилово', 'rayon-dorogomilovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (308, 'район Крылатское', 'rayon-krylatskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (309, 'район Кунцево', 'rayon-kuncevo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (310, 'Можайский район', 'mozhayskiy-rayon-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (311, 'район Ново-Переделкино', 'rayon-novo-peredelkino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (312, 'район Очаково-Матвеевское', 'rayon-ochakovo-matveevskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (313, 'район Проспект Вернадского', 'rayon-prospekt-vernadskogo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (314, 'район Раменки', 'rayon-ramenki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (315, 'район Солнцево', 'rayon-solncevo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (316, 'район Тропарёво-Никулино', 'rayon-troparevo-nikulino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (317, 'район Филёвский Парк', 'rayon-filevskiy-park-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (318, 'район Фили-Давыдково', 'rayon-fili-davydkovo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (319, 'район Куркино', 'rayon-kurkino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (320, 'район Митино', 'rayon-mitino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (321, 'район Покровское-Стрешнево', 'rayon-pokrovskoe-streshnevo-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (322, 'район Северное Тушино', 'rayon-severnoe-tushino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (323, 'район Хорошёво-Мнёвники', 'rayon-horoshevo-mnevniki-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (324, 'район Щукино', 'rayon-shchukino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (325, 'район Южное Тушино', 'rayon-yuzhnoe-tushino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (326, 'район Строгино', 'rayon-strogino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (327, 'район СП Внуковское', 'rayon-sp-vnukovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (328, 'район СП Воскресенское', 'rayon-sp-voskresenskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (329, 'район СП Десёновское', 'rayon-sp-desenovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (330, 'район СП Кокошкино', 'rayon-sp-kokoshkino-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (331, 'район СП Марушкинское', 'rayon-sp-marushkinskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (332, 'район СП Московский', 'rayon-sp-moskovskiy-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (333, 'район СП Мосрентген', 'rayon-sp-mosrentgen-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (334, 'район СП Рязановское', 'rayon-sp-ryazanovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (335, 'район СП Сосенское', 'rayon-sp-sosenskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (336, 'район СП Филимонковское', 'rayon-sp-filimonkovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (337, 'район ГО Щербинка', 'rayon-go-shcherbinka-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (338, 'район СП Вороновское', 'rayon-sp-voronovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (339, 'район СП Киевский', 'rayon-sp-kievskiy-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (340, 'район СП Клёновское', 'rayon-sp-klenovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (341, 'район СП Краснопахорское', 'rayon-sp-krasnopahorskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (342, 'район СП Михайлово-Ярцевское', 'rayon-sp-mihaylovo-yarcevskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (343, 'район СП Новофёдоровское', 'rayon-sp-novofedorovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (344, 'район СП Первомайское', 'rayon-sp-pervomayskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (345, 'район СП Роговское', 'rayon-sp-rogovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (346, 'район ГО Троицк', 'rayon-go-troick-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (347, 'район СП Щаповское', 'rayon-sp-shchapovskoe-1', 11);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (348, 'район Арбат', 'rayon-arbat-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (349, 'Басманный район', 'basmannyy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (350, 'район Замоскворечье', 'rayon-zamoskvoreche-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (351, 'Красносельский район', 'krasnoselskiy-rayon-3', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (352, 'Мещанский район', 'meshchanskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (353, 'Пресненский район', 'presnenskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (354, 'Таганский район', 'taganskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (355, 'Тверской район', 'tverskoy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (356, 'район Хамовники', 'rayon-hamovniki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (357, 'район Якиманка', 'rayon-yakimanka-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (358, 'район Аэропорт', 'rayon-aeroport-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (359, 'Беговой район', 'begovoy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (360, 'Бескудниковский район', 'beskudnikovskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (361, 'Войковский район', 'voykovskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (362, 'район Восточное Дегунино', 'rayon-vostochnoe-degunino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (363, 'Головинский район', 'golovinskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (364, 'Дмитровский район', 'dmitrovskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (365, 'район Западное Дегунино', 'rayon-zapadnoe-degunino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (366, 'район Коптево', 'rayon-koptevo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (367, 'Левобережный район', 'levoberezhnyy-rayon-3', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (368, 'Молжаниновский район', 'molzhaninovskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (369, 'Савёловский район', 'savelovskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (370, 'район Сокол', 'rayon-sokol-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (371, 'Тимирязевский район', 'timiryazevskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (372, 'район Ховрино', 'rayon-hovrino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (373, 'Хорошёвский район', 'horoshevskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (374, 'Алексеевский район', 'alekseevskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (375, 'Алтуфьевский район', 'altufevskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (376, 'Бабушкинский район', 'babushkinskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (377, 'район Бибирево', 'rayon-bibirevo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (378, 'Бутырский район', 'butyrskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (379, 'район Лианозово', 'rayon-lianozovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (380, 'Лосиноостровский район', 'losinoostrovskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (381, 'район Марфино', 'rayon-marfino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (382, 'район Марьина Роща', 'rayon-marina-roshcha-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (383, 'Останкинский район', 'ostankinskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (384, 'район Отрадное', 'rayon-otradnoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (385, 'район Ростокино', 'rayon-rostokino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (386, 'район Свиблово', 'rayon-sviblovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (387, 'Северный район', 'severnyy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (388, 'район Северное Медведково', 'rayon-severnoe-medvedkovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (389, 'район Южное Медведково', 'rayon-yuzhnoe-medvedkovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (390, 'Ярославский район', 'yaroslavskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (391, 'район Богородское', 'rayon-bogorodskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (392, 'район Вешняки', 'rayon-veshnyaki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (393, 'Восточный район', 'vostochnyy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (394, 'район Восточное Измайлово', 'rayon-vostochnoe-izmaylovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (395, 'район Гольяново', 'rayon-golyanovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (396, 'район Ивановское', 'rayon-ivanovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (397, 'район Измайлово', 'rayon-izmaylovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (398, 'Косино-Ухтомский район', 'kosino-uhtomskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (399, 'район Метрогородок', 'rayon-metrogorodok-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (400, 'район Новогиреево', 'rayon-novogireevo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (401, 'район Новокосино', 'rayon-novokosino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (402, 'район Перово', 'rayon-perovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (403, 'район Преображенское', 'rayon-preobrazhenskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (404, 'район Северное Измайлово', 'rayon-severnoe-izmaylovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (405, 'район Соколиная Гора', 'rayon-sokolinaya-gora-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (406, 'район Сокольники', 'rayon-sokolniki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (407, 'район Выхино-Жулебино', 'rayon-vyhino-zhulebino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (408, 'район Капотня', 'rayon-kapotnya-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (409, 'район Кузьминки', 'rayon-kuzminki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (410, 'район Лефортово', 'rayon-lefortovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (411, 'район Люблино', 'rayon-lyublino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (412, 'район Марьино', 'rayon-marino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (413, 'район Некрасовка', 'rayon-nekrasovka-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (414, 'Нижегородский район', 'nizhegorodskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (415, 'район Печатники', 'rayon-pechatniki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (416, 'Рязанский район', 'ryazanskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (417, 'район Текстильщики', 'rayon-tekstilshchiki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (418, 'Южнопортовый район', 'yuzhnoportovyy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (419, 'район Бирюлёво Восточное', 'rayon-biryulevo-vostochnoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (420, 'район Бирюлёво Западное', 'rayon-biryulevo-zapadnoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (421, 'район Братеево', 'rayon-brateevo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (422, 'Даниловский район', 'danilovskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (423, 'Донской район', 'donskoy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (424, 'район Зябликово', 'rayon-zyablikovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (425, 'район Москворечье-Сабурово', 'rayon-moskvoreche-saburovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (426, 'район Нагатино-Садовники', 'rayon-nagatino-sadovniki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (427, 'район Нагатинский Затон', 'rayon-nagatinskiy-zaton-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (428, 'Нагорный район', 'nagornyy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (429, 'район Орехово-Борисово Северное', 'rayon-orehovo-borisovo-severnoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (430, 'район Орехово-Борисово Южное', 'rayon-orehovo-borisovo-yuzhnoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (431, 'район Царицыно', 'rayon-caricyno-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (432, 'район Чертаново Северное', 'rayon-chertanovo-severnoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (433, 'район Чертаново Центральное', 'rayon-chertanovo-centralnoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (434, 'район Чертаново Южное', 'rayon-chertanovo-yuzhnoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (435, 'Академический район', 'akademicheskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (436, 'Гагаринский район', 'gagarinskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (437, 'район Зюзино', 'rayon-zyuzino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (438, 'район Коньково', 'rayon-konkovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (439, 'район Котловка', 'rayon-kotlovka-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (440, 'Ломоносовский район', 'lomonosovskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (441, 'Обручевский район', 'obruchevskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (442, 'район Северное Бутово', 'rayon-severnoe-butovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (443, 'район Тёплый Стан', 'rayon-teplyy-stan-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (444, 'район Черёмушки', 'rayon-cheremushki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (445, 'район Южное Бутово', 'rayon-yuzhnoe-butovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (446, 'район Ясенево', 'rayon-yasenevo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (447, 'район Дорогомилово', 'rayon-dorogomilovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (448, 'район Крылатское', 'rayon-krylatskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (449, 'район Кунцево', 'rayon-kuncevo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (450, 'Можайский район', 'mozhayskiy-rayon-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (451, 'район Ново-Переделкино', 'rayon-novo-peredelkino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (452, 'район Очаково-Матвеевское', 'rayon-ochakovo-matveevskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (453, 'район Проспект Вернадского', 'rayon-prospekt-vernadskogo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (454, 'район Раменки', 'rayon-ramenki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (455, 'район Солнцево', 'rayon-solncevo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (456, 'район Тропарёво-Никулино', 'rayon-troparevo-nikulino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (457, 'район Филёвский Парк', 'rayon-filevskiy-park-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (458, 'район Фили-Давыдково', 'rayon-fili-davydkovo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (459, 'район Куркино', 'rayon-kurkino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (460, 'район Митино', 'rayon-mitino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (461, 'район Покровское-Стрешнево', 'rayon-pokrovskoe-streshnevo-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (462, 'район Северное Тушино', 'rayon-severnoe-tushino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (463, 'район Хорошёво-Мнёвники', 'rayon-horoshevo-mnevniki-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (464, 'район Щукино', 'rayon-shchukino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (465, 'район Южное Тушино', 'rayon-yuzhnoe-tushino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (466, 'район Строгино', 'rayon-strogino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (467, 'район СП Внуковское', 'rayon-sp-vnukovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (468, 'район СП Воскресенское', 'rayon-sp-voskresenskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (469, 'район СП Десёновское', 'rayon-sp-desenovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (470, 'район СП Кокошкино', 'rayon-sp-kokoshkino-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (471, 'район СП Марушкинское', 'rayon-sp-marushkinskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (472, 'район СП Московский', 'rayon-sp-moskovskiy-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (473, 'район СП Мосрентген', 'rayon-sp-mosrentgen-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (474, 'район СП Рязановское', 'rayon-sp-ryazanovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (475, 'район СП Сосенское', 'rayon-sp-sosenskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (476, 'район СП Филимонковское', 'rayon-sp-filimonkovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (477, 'район ГО Щербинка', 'rayon-go-shcherbinka-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (478, 'район СП Вороновское', 'rayon-sp-voronovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (479, 'район СП Киевский', 'rayon-sp-kievskiy-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (480, 'район СП Клёновское', 'rayon-sp-klenovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (481, 'район СП Краснопахорское', 'rayon-sp-krasnopahorskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (482, 'район СП Михайлово-Ярцевское', 'rayon-sp-mihaylovo-yarcevskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (483, 'район СП Новофёдоровское', 'rayon-sp-novofedorovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (484, 'район СП Первомайское', 'rayon-sp-pervomayskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (485, 'район СП Роговское', 'rayon-sp-rogovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (486, 'район ГО Троицк', 'rayon-go-troick-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (487, 'район СП Щаповское', 'rayon-sp-shchapovskoe-2', 12);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (488, 'Центральный район', 'centralnyy-rayon-5', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (489, 'Советский район', 'sovetskiy-rayon-5', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (490, 'Первомайский район', 'pervomayskiy-rayon-1', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (491, 'Октябрьский район', 'oktyabrskiy-rayon-2', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (492, 'Ленинский район', 'leninskiy-rayon-4', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (493, 'Кировский район', 'kirovskiy-rayon-5', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (494, 'Калининский район', 'kalininskiy-rayon-1', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (495, 'Заельцовский район', 'zaelcovskiy-rayon', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (496, 'Железнодорожный район', 'zheleznodorozhnyy-rayon-3', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (497, 'Дзержинский район', 'dzerzhinskiy-rayon-1', 13);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (498, 'Центральный район', 'centralnyy-rayon-6', 14);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (499, 'Советский район', 'sovetskiy-rayon-6', 14);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (500, 'Октябрьский район', 'oktyabrskiy-rayon-3', 14);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (501, 'Ленинский район', 'leninskiy-rayon-5', 14);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (502, 'Кировский район', 'kirovskiy-rayon-6', 14);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (503, 'Свердловский район', 'sverdlovskiy-rayon-1', 15);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (504, 'Орджоникидзевский район', 'ordzhonikidzevskiy-rayon-1', 15);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (505, 'район Новые Ляды', 'rayon-novye-lyady', 15);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (506, 'Мотовилихинский район', 'motovilihinskiy-rayon', 15);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (507, 'Ленинский район', 'leninskiy-rayon-6', 15);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (508, 'Кировский район', 'kirovskiy-rayon-7', 15);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (509, 'Индустриальный район', 'industrialnyy-rayon', 15);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (510, 'Дзержинский район', 'dzerzhinskiy-rayon-2', 15);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (511, 'район Арбат', 'rayon-arbat-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (512, 'Басманный район', 'basmannyy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (513, 'район Замоскворечье', 'rayon-zamoskvoreche-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (514, 'Красносельский район', 'krasnoselskiy-rayon-4', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (515, 'Мещанский район', 'meshchanskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (516, 'Пресненский район', 'presnenskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (517, 'Таганский район', 'taganskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (518, 'Тверской район', 'tverskoy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (519, 'район Хамовники', 'rayon-hamovniki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (520, 'район Якиманка', 'rayon-yakimanka-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (521, 'район Аэропорт', 'rayon-aeroport-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (522, 'Беговой район', 'begovoy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (523, 'Бескудниковский район', 'beskudnikovskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (524, 'Войковский район', 'voykovskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (525, 'район Восточное Дегунино', 'rayon-vostochnoe-degunino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (526, 'Головинский район', 'golovinskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (527, 'Дмитровский район', 'dmitrovskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (528, 'район Западное Дегунино', 'rayon-zapadnoe-degunino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (529, 'район Коптево', 'rayon-koptevo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (530, 'Левобережный район', 'levoberezhnyy-rayon-4', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (531, 'Молжаниновский район', 'molzhaninovskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (532, 'Савёловский район', 'savelovskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (533, 'район Сокол', 'rayon-sokol-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (534, 'Тимирязевский район', 'timiryazevskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (535, 'район Ховрино', 'rayon-hovrino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (536, 'Хорошёвский район', 'horoshevskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (537, 'Алексеевский район', 'alekseevskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (538, 'Алтуфьевский район', 'altufevskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (539, 'Бабушкинский район', 'babushkinskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (540, 'район Бибирево', 'rayon-bibirevo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (541, 'Бутырский район', 'butyrskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (542, 'район Лианозово', 'rayon-lianozovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (543, 'Лосиноостровский район', 'losinoostrovskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (544, 'район Марфино', 'rayon-marfino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (545, 'район Марьина Роща', 'rayon-marina-roshcha-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (546, 'Останкинский район', 'ostankinskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (547, 'район Отрадное', 'rayon-otradnoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (548, 'район Ростокино', 'rayon-rostokino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (549, 'район Свиблово', 'rayon-sviblovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (550, 'Северный район', 'severnyy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (551, 'район Северное Медведково', 'rayon-severnoe-medvedkovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (552, 'район Южное Медведково', 'rayon-yuzhnoe-medvedkovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (553, 'Ярославский район', 'yaroslavskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (554, 'район Богородское', 'rayon-bogorodskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (555, 'район Вешняки', 'rayon-veshnyaki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (556, 'Восточный район', 'vostochnyy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (557, 'район Восточное Измайлово', 'rayon-vostochnoe-izmaylovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (558, 'район Гольяново', 'rayon-golyanovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (559, 'район Ивановское', 'rayon-ivanovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (560, 'район Измайлово', 'rayon-izmaylovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (561, 'Косино-Ухтомский район', 'kosino-uhtomskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (562, 'район Метрогородок', 'rayon-metrogorodok-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (563, 'район Новогиреево', 'rayon-novogireevo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (564, 'район Новокосино', 'rayon-novokosino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (565, 'район Перово', 'rayon-perovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (566, 'район Преображенское', 'rayon-preobrazhenskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (567, 'район Северное Измайлово', 'rayon-severnoe-izmaylovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (568, 'район Соколиная Гора', 'rayon-sokolinaya-gora-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (569, 'район Сокольники', 'rayon-sokolniki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (570, 'район Выхино-Жулебино', 'rayon-vyhino-zhulebino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (571, 'район Капотня', 'rayon-kapotnya-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (572, 'район Кузьминки', 'rayon-kuzminki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (573, 'район Лефортово', 'rayon-lefortovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (574, 'район Люблино', 'rayon-lyublino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (575, 'район Марьино', 'rayon-marino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (576, 'район Некрасовка', 'rayon-nekrasovka-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (577, 'Нижегородский район', 'nizhegorodskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (578, 'район Печатники', 'rayon-pechatniki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (579, 'Рязанский район', 'ryazanskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (580, 'район Текстильщики', 'rayon-tekstilshchiki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (581, 'Южнопортовый район', 'yuzhnoportovyy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (582, 'район Бирюлёво Восточное', 'rayon-biryulevo-vostochnoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (583, 'район Бирюлёво Западное', 'rayon-biryulevo-zapadnoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (584, 'район Братеево', 'rayon-brateevo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (585, 'Даниловский район', 'danilovskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (586, 'Донской район', 'donskoy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (587, 'район Зябликово', 'rayon-zyablikovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (588, 'район Москворечье-Сабурово', 'rayon-moskvoreche-saburovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (589, 'район Нагатино-Садовники', 'rayon-nagatino-sadovniki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (590, 'район Нагатинский Затон', 'rayon-nagatinskiy-zaton-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (591, 'Нагорный район', 'nagornyy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (592, 'район Орехово-Борисово Северное', 'rayon-orehovo-borisovo-severnoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (593, 'район Орехово-Борисово Южное', 'rayon-orehovo-borisovo-yuzhnoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (594, 'район Царицыно', 'rayon-caricyno-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (595, 'район Чертаново Северное', 'rayon-chertanovo-severnoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (596, 'район Чертаново Центральное', 'rayon-chertanovo-centralnoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (597, 'район Чертаново Южное', 'rayon-chertanovo-yuzhnoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (598, 'Академический район', 'akademicheskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (599, 'Гагаринский район', 'gagarinskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (600, 'район Зюзино', 'rayon-zyuzino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (601, 'район Коньково', 'rayon-konkovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (602, 'район Котловка', 'rayon-kotlovka-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (603, 'Ломоносовский район', 'lomonosovskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (604, 'Обручевский район', 'obruchevskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (605, 'район Северное Бутово', 'rayon-severnoe-butovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (606, 'район Тёплый Стан', 'rayon-teplyy-stan-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (607, 'район Черёмушки', 'rayon-cheremushki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (608, 'район Южное Бутово', 'rayon-yuzhnoe-butovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (609, 'район Ясенево', 'rayon-yasenevo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (610, 'район Дорогомилово', 'rayon-dorogomilovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (611, 'район Крылатское', 'rayon-krylatskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (612, 'район Кунцево', 'rayon-kuncevo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (613, 'Можайский район', 'mozhayskiy-rayon-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (614, 'район Ново-Переделкино', 'rayon-novo-peredelkino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (615, 'район Очаково-Матвеевское', 'rayon-ochakovo-matveevskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (616, 'район Проспект Вернадского', 'rayon-prospekt-vernadskogo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (617, 'район Раменки', 'rayon-ramenki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (618, 'район Солнцево', 'rayon-solncevo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (619, 'район Тропарёво-Никулино', 'rayon-troparevo-nikulino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (620, 'район Филёвский Парк', 'rayon-filevskiy-park-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (621, 'район Фили-Давыдково', 'rayon-fili-davydkovo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (622, 'район Куркино', 'rayon-kurkino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (623, 'район Митино', 'rayon-mitino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (624, 'район Покровское-Стрешнево', 'rayon-pokrovskoe-streshnevo-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (625, 'район Северное Тушино', 'rayon-severnoe-tushino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (626, 'район Хорошёво-Мнёвники', 'rayon-horoshevo-mnevniki-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (627, 'район Щукино', 'rayon-shchukino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (628, 'район Южное Тушино', 'rayon-yuzhnoe-tushino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (629, 'район Строгино', 'rayon-strogino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (630, 'район СП Внуковское', 'rayon-sp-vnukovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (631, 'район СП Воскресенское', 'rayon-sp-voskresenskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (632, 'район СП Десёновское', 'rayon-sp-desenovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (633, 'район СП Кокошкино', 'rayon-sp-kokoshkino-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (634, 'район СП Марушкинское', 'rayon-sp-marushkinskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (635, 'район СП Московский', 'rayon-sp-moskovskiy-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (636, 'район СП Мосрентген', 'rayon-sp-mosrentgen-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (637, 'район СП Рязановское', 'rayon-sp-ryazanovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (638, 'район СП Сосенское', 'rayon-sp-sosenskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (639, 'район СП Филимонковское', 'rayon-sp-filimonkovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (640, 'район ГО Щербинка', 'rayon-go-shcherbinka-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (641, 'район СП Вороновское', 'rayon-sp-voronovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (642, 'район СП Киевский', 'rayon-sp-kievskiy-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (643, 'район СП Клёновское', 'rayon-sp-klenovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (644, 'район СП Краснопахорское', 'rayon-sp-krasnopahorskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (645, 'район СП Михайлово-Ярцевское', 'rayon-sp-mihaylovo-yarcevskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (646, 'район СП Новофёдоровское', 'rayon-sp-novofedorovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (647, 'район СП Первомайское', 'rayon-sp-pervomayskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (648, 'район СП Роговское', 'rayon-sp-rogovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (649, 'район ГО Троицк', 'rayon-go-troick-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (650, 'район СП Щаповское', 'rayon-sp-shchapovskoe-3', 16);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (651, 'Советский район', 'sovetskiy-rayon-7', 17);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (652, 'Самарский район', 'samarskiy-rayon', 17);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (653, 'Промышленный район', 'promyshlennyy-rayon', 17);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (654, 'Октябрьский район', 'oktyabrskiy-rayon-4', 17);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (655, 'Ленинский район', 'leninskiy-rayon-7', 17);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (656, 'Куйбышевский район', 'kuybyshevskiy-rayon', 17);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (657, 'Красноглинский район', 'krasnoglinskiy-rayon', 17);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (658, 'Кировский район', 'kirovskiy-rayon-8', 17);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (659, 'Железнодорожный район', 'zheleznodorozhnyy-rayon-4', 17);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (660, 'Фрунзенский район', 'frunzenskiy-rayon-2', 19);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (661, 'Октябрьский район', 'oktyabrskiy-rayon-5', 19);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (662, 'Ленинский район', 'leninskiy-rayon-8', 19);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (663, 'Кировский район', 'kirovskiy-rayon-9', 19);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (664, 'Заводской район', 'zavodskoy-rayon', 19);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (665, 'Волжский район', 'volzhskiy-rayon', 19);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (666, 'район Арбат', 'rayon-arbat-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (667, 'Басманный район', 'basmannyy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (668, 'район Замоскворечье', 'rayon-zamoskvoreche-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (669, 'Красносельский район', 'krasnoselskiy-rayon-5', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (670, 'Мещанский район', 'meshchanskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (671, 'Пресненский район', 'presnenskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (672, 'Таганский район', 'taganskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (673, 'Тверской район', 'tverskoy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (674, 'район Хамовники', 'rayon-hamovniki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (675, 'район Якиманка', 'rayon-yakimanka-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (676, 'район Аэропорт', 'rayon-aeroport-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (677, 'Беговой район', 'begovoy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (678, 'Бескудниковский район', 'beskudnikovskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (679, 'Войковский район', 'voykovskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (680, 'район Восточное Дегунино', 'rayon-vostochnoe-degunino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (681, 'Головинский район', 'golovinskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (682, 'Дмитровский район', 'dmitrovskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (683, 'район Западное Дегунино', 'rayon-zapadnoe-degunino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (684, 'район Коптево', 'rayon-koptevo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (685, 'Левобережный район', 'levoberezhnyy-rayon-5', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (686, 'Молжаниновский район', 'molzhaninovskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (687, 'Савёловский район', 'savelovskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (688, 'район Сокол', 'rayon-sokol-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (689, 'Тимирязевский район', 'timiryazevskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (690, 'район Ховрино', 'rayon-hovrino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (691, 'Хорошёвский район', 'horoshevskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (692, 'Алексеевский район', 'alekseevskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (693, 'Алтуфьевский район', 'altufevskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (694, 'Бабушкинский район', 'babushkinskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (695, 'район Бибирево', 'rayon-bibirevo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (696, 'Бутырский район', 'butyrskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (697, 'район Лианозово', 'rayon-lianozovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (698, 'Лосиноостровский район', 'losinoostrovskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (699, 'район Марфино', 'rayon-marfino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (700, 'район Марьина Роща', 'rayon-marina-roshcha-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (701, 'Останкинский район', 'ostankinskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (702, 'район Отрадное', 'rayon-otradnoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (703, 'район Ростокино', 'rayon-rostokino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (704, 'район Свиблово', 'rayon-sviblovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (705, 'Северный район', 'severnyy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (706, 'район Северное Медведково', 'rayon-severnoe-medvedkovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (707, 'район Южное Медведково', 'rayon-yuzhnoe-medvedkovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (708, 'Ярославский район', 'yaroslavskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (709, 'район Богородское', 'rayon-bogorodskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (710, 'район Вешняки', 'rayon-veshnyaki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (711, 'Восточный район', 'vostochnyy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (712, 'район Восточное Измайлово', 'rayon-vostochnoe-izmaylovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (713, 'район Гольяново', 'rayon-golyanovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (714, 'район Ивановское', 'rayon-ivanovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (715, 'район Измайлово', 'rayon-izmaylovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (716, 'Косино-Ухтомский район', 'kosino-uhtomskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (717, 'район Метрогородок', 'rayon-metrogorodok-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (718, 'район Новогиреево', 'rayon-novogireevo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (719, 'район Новокосино', 'rayon-novokosino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (720, 'район Перово', 'rayon-perovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (721, 'район Преображенское', 'rayon-preobrazhenskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (722, 'район Северное Измайлово', 'rayon-severnoe-izmaylovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (723, 'район Соколиная Гора', 'rayon-sokolinaya-gora-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (724, 'район Сокольники', 'rayon-sokolniki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (725, 'район Выхино-Жулебино', 'rayon-vyhino-zhulebino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (726, 'район Капотня', 'rayon-kapotnya-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (727, 'район Кузьминки', 'rayon-kuzminki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (728, 'район Лефортово', 'rayon-lefortovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (729, 'район Люблино', 'rayon-lyublino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (730, 'район Марьино', 'rayon-marino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (731, 'район Некрасовка', 'rayon-nekrasovka-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (732, 'Нижегородский район', 'nizhegorodskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (733, 'район Печатники', 'rayon-pechatniki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (734, 'Рязанский район', 'ryazanskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (735, 'район Текстильщики', 'rayon-tekstilshchiki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (736, 'Южнопортовый район', 'yuzhnoportovyy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (737, 'район Бирюлёво Восточное', 'rayon-biryulevo-vostochnoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (738, 'район Бирюлёво Западное', 'rayon-biryulevo-zapadnoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (739, 'район Братеево', 'rayon-brateevo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (740, 'Даниловский район', 'danilovskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (741, 'Донской район', 'donskoy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (742, 'район Зябликово', 'rayon-zyablikovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (743, 'район Москворечье-Сабурово', 'rayon-moskvoreche-saburovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (744, 'район Нагатино-Садовники', 'rayon-nagatino-sadovniki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (745, 'район Нагатинский Затон', 'rayon-nagatinskiy-zaton-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (746, 'Нагорный район', 'nagornyy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (747, 'район Орехово-Борисово Северное', 'rayon-orehovo-borisovo-severnoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (748, 'район Орехово-Борисово Южное', 'rayon-orehovo-borisovo-yuzhnoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (749, 'район Царицыно', 'rayon-caricyno-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (750, 'район Чертаново Северное', 'rayon-chertanovo-severnoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (751, 'район Чертаново Центральное', 'rayon-chertanovo-centralnoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (752, 'район Чертаново Южное', 'rayon-chertanovo-yuzhnoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (753, 'Академический район', 'akademicheskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (754, 'Гагаринский район', 'gagarinskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (755, 'район Зюзино', 'rayon-zyuzino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (756, 'район Коньково', 'rayon-konkovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (757, 'район Котловка', 'rayon-kotlovka-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (758, 'Ломоносовский район', 'lomonosovskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (759, 'Обручевский район', 'obruchevskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (760, 'район Северное Бутово', 'rayon-severnoe-butovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (761, 'район Тёплый Стан', 'rayon-teplyy-stan-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (762, 'район Черёмушки', 'rayon-cheremushki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (763, 'район Южное Бутово', 'rayon-yuzhnoe-butovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (764, 'район Ясенево', 'rayon-yasenevo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (765, 'район Дорогомилово', 'rayon-dorogomilovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (766, 'район Крылатское', 'rayon-krylatskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (767, 'район Кунцево', 'rayon-kuncevo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (768, 'Можайский район', 'mozhayskiy-rayon-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (769, 'район Ново-Переделкино', 'rayon-novo-peredelkino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (770, 'район Очаково-Матвеевское', 'rayon-ochakovo-matveevskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (771, 'район Проспект Вернадского', 'rayon-prospekt-vernadskogo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (772, 'район Раменки', 'rayon-ramenki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (773, 'район Солнцево', 'rayon-solncevo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (774, 'район Тропарёво-Никулино', 'rayon-troparevo-nikulino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (775, 'район Филёвский Парк', 'rayon-filevskiy-park-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (776, 'район Фили-Давыдково', 'rayon-fili-davydkovo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (777, 'район Куркино', 'rayon-kurkino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (778, 'район Митино', 'rayon-mitino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (779, 'район Покровское-Стрешнево', 'rayon-pokrovskoe-streshnevo-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (780, 'район Северное Тушино', 'rayon-severnoe-tushino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (781, 'район Хорошёво-Мнёвники', 'rayon-horoshevo-mnevniki-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (782, 'район Щукино', 'rayon-shchukino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (783, 'район Южное Тушино', 'rayon-yuzhnoe-tushino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (784, 'район Строгино', 'rayon-strogino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (785, 'район СП Внуковское', 'rayon-sp-vnukovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (786, 'район СП Воскресенское', 'rayon-sp-voskresenskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (787, 'район СП Десёновское', 'rayon-sp-desenovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (788, 'район СП Кокошкино', 'rayon-sp-kokoshkino-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (789, 'район СП Марушкинское', 'rayon-sp-marushkinskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (790, 'район СП Московский', 'rayon-sp-moskovskiy-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (791, 'район СП Мосрентген', 'rayon-sp-mosrentgen-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (792, 'район СП Рязановское', 'rayon-sp-ryazanovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (793, 'район СП Сосенское', 'rayon-sp-sosenskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (794, 'район СП Филимонковское', 'rayon-sp-filimonkovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (795, 'район ГО Щербинка', 'rayon-go-shcherbinka-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (796, 'район СП Вороновское', 'rayon-sp-voronovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (797, 'район СП Киевский', 'rayon-sp-kievskiy-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (798, 'район СП Клёновское', 'rayon-sp-klenovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (799, 'район СП Краснопахорское', 'rayon-sp-krasnopahorskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (800, 'район СП Михайлово-Ярцевское', 'rayon-sp-mihaylovo-yarcevskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (801, 'район СП Новофёдоровское', 'rayon-sp-novofedorovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (802, 'район СП Первомайское', 'rayon-sp-pervomayskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (803, 'район СП Роговское', 'rayon-sp-rogovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (804, 'район ГО Троицк', 'rayon-go-troick-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (805, 'район СП Щаповское', 'rayon-sp-shchapovskoe-4', 20);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (806, 'Советский район', 'sovetskiy-rayon-8', 21);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (807, 'Орджоникидзевский', 'ordzhonikidzevskiy', 21);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (808, 'Октябрьский район', 'oktyabrskiy-rayon-6', 21);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (809, 'Ленинский район', 'leninskiy-rayon-9', 21);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (810, 'Кировский район', 'kirovskiy-rayon-10', 21);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (811, 'Калининский район', 'kalininskiy-rayon-2', 21);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (812, 'Дёмский район', 'demskiy-rayon', 21);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (813, 'Центральный район', 'centralnyy-rayon-7', 22);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (814, 'Краснофлотский район', 'krasnoflotskiy-rayon', 22);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (815, 'Кировский район', 'kirovskiy-rayon-11', 22);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (816, 'Индустриальный район', 'industrialnyy-rayon-1', 22);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (817, 'Железнодорожный район', 'zheleznodorozhnyy-rayon-5', 22);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (818, 'Центральный район', 'centralnyy-rayon-8', 23);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (819, 'Тракторозаводский район', 'traktorozavodskiy-rayon-1', 23);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (820, 'Советский район', 'sovetskiy-rayon-9', 23);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (821, 'Металлургический район', 'metallurgicheskiy-rayon', 23);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (822, 'Ленинский район', 'leninskiy-rayon-10', 23);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (823, 'Курчатовский район', 'kurchatovskiy-rayon', 23);
INSERT INTO city_districts (id, name, slug, city_id) VALUES (824, 'Калининский район', 'kalininskiy-rayon-3', 23);");
    }
}
