version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
      - elasticsearch
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
      - elasticsearch
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    tty: true
  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"
  node:
    build:
      context: ./
      dockerfile: docker/node.docker
    volumes:
      - ./:/var/www
    tty: true
    ports:
      - "6379:6379"
      - "6001:6001"
    links:
      - redis
    command: npm run watch
  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
  redis:
    image: redis:3.0
    ports:
      - "63791:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/hunspell"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/:/usr/share/elasticsearch/config/hunspell
    ports:
      - "9201:9200"
